language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: JOAQjRftpqMdz2vQR3O0bWabxXx2M1kNnnm9uuHy2lEKOw9pldnN3Uo9enuIWKZirraVDDRlON85IoeLDI/9vfXdlNWqGCYQO39+jMfM0fPbCXfeWjD5/EC45nJMDnSdB9K+oOmcO4OD9gvpB1inwo+Ua4rmrks6pAgOHTDJR1+WYjs0dqMMeeem08uLd6BJOvm+n8bMbrv8Ac6PRo94uXkqhMbnTBHD2emLPDg+FXUcEaXkJcTjwU3/h2jT7D94mlKhA/AmJm+5Us/SlOp+AV3/fuSkPindb3Vu9GgQUp50ubSpuG/bzThBlRvVDggH9RllH5XAYLKifX5BcVFcoaTeJlT75AFR2OhctcRksorgfgDLvMN1HOniHz2xWxgfyU7Y5XvcUzJK3MaIjZL31Ta9MzI0QiqVkT1TyZ2c8RItE3EAPLS7Cr+Dg/kB9XFYAsTsHu6PYf5x+qS30zzr/KSeFLenxLdEfmzGxH1tfxleG6uCriA/ZqsKQO/KUNwbXG5LFGNle8nIrE2yNIQW92K2uV6zy7RXdrZwKBeQZxCqj5RP5FX5SCFKEeiSJy0idFtwAN9P+3I7wQpYVivcJaIXkqsLE+DjQGKBhn+tipXqjOjX5tjetGBky8zwp8AJZbDEGGYwtkKkdiwq6LO6mxrWxh3PoA7ISDj0Bxjn82k=
  on:
    tags: true
    repo: noflo/noflo-geo
